CREATE TABLE IF NOT EXISTS images (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  owner_id UUID NOT NULL,
  height SMALLINT NOT NULL,
  width SMALLINT NOT NULL,
  mime VARCHAR(120) NOT NULL,
  url VARCHAR(255) NOT NULL UNIQUE,
  filename VARCHAR(120) NOT NULL UNIQUE,
  size INTEGER NOT NULL,
  image BYTEA NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(owner_id) REFERENCES users(id)
);
